services:
  font_awesome_inserttag.hook_listener:
    class: Netzmacht\Contao\FontAwesomeInsertTag\HookListener
    arguments:
      - "%font_awesome_inserttag.icon_template%"
      - "%font_awesome_inserttag.stack_template%"
